### ISSUE TITLE
SyntaxError: Unexpected Identifier (waw_data.js)

### ISSUE THREAD

**Issue by w3aryb0arpig** [mnafees/UhOh#3]
Upon trying to run this script, there appears to be an error with the WASecretBundle:

```
node index.js "My Friend"
/Users/me/Desktop/UhOh-master/waw_data.js:2
module.exports.WASecretBundle = "{"key":"5KX8HO9ZmNxgoQuU6bySgm9UtsOAJSMDJscXWsy6qASdU=","encKey":"OrzX9o/7nXJKmBATEW60ipan+MVHp7zEDkejdmST61uHg=","macKey":"5KX8HO9ZmNxgoQdkwkdmSgm9UtsOxWOvLcXWsy6qASdU="}"; // Copy-paste your WASecretBundle
                                   ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:588:28)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/me/Desktop/UhOh-master/index.js:9:18)
```

I've checked "" within this field and it appears correct.

Any suggestions?

**Comment by w3aryb0arpig** [comment]
Ignore last update - no invert commas required around the "WASecretBundle"
